apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-server-app
  template:
    metadata:
      labels:
        app: go-server-app
    spec:
      containers:
      - image: localhost:32000/go-server-app-image
        name: go-server-app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
